import type { editor } from "monaco-editor";
import type { ITheme } from "@xterm/xterm";
import type { ThemePalette } from "./palette.js";

export const MONACO_THEME_NAME = "mainly-adaptive";

export function monacoTheme({ mode, colors: c }: ThemePalette): editor.IStandaloneThemeData {
  return {
    base: mode === "dark" ? "vs-dark" : "vs",
    inherit: false,
    colors: {
      focusBorder: c.fg,
      foreground: c.fg,
      "editor.background": c.canvas,
      "editor.foreground": c.fg,
      "editorLineNumber.foreground": c.muted,
      "editorLineNumber.activeForeground": c.fg,
      "editorCursor.foreground": c.fg,
      "editor.selectionBackground": c.selected,
      "editor.selectionForeground": c.fg,
      "editor.inactiveSelectionBackground": c.hover,
      "editor.selectionHighlightBackground": c.hover,
      "editor.wordHighlightBackground": c.hover,
      "editor.wordHighlightStrongBackground": c.selected,
      "editor.findMatchBackground": c.selected,
      "editor.findMatchHighlightBackground": c.hover,
      "editor.findMatchBorder": c.muted,
      "editor.findMatchHighlightBorder": c["border-strong"],
      "editor.lineHighlightBackground": c.panel,
      "editorIndentGuide.background1": c.border,
      "editorIndentGuide.activeBackground1": c["border-strong"],
      "editorBracketMatch.background": c.selected,
      "editorBracketMatch.border": c["border-strong"],
      "editorBracketHighlight.foreground1": c.secondary,
      "editorBracketHighlight.foreground2": c.secondary,
      "editorBracketHighlight.foreground3": c.secondary,
      "editorBracketHighlight.foreground4": c.secondary,
      "editorBracketHighlight.foreground5": c.secondary,
      "editorBracketHighlight.foreground6": c.secondary,
      "editorBracketHighlight.unexpectedBracket.foreground": c.danger,
      "editorGhostText.foreground": c.muted,
      "editorSuggestWidget.background": c.raised,
      "editorSuggestWidget.foreground": c.fg,
      "editorSuggestWidget.border": c["border-strong"],
      "editorSuggestWidget.selectedBackground": c.selected,
      "editorSuggestWidget.selectedForeground": c.fg,
      "editorSuggestWidget.highlightForeground": c.fg,
      "editorSuggestWidget.focusHighlightForeground": c.fg,
      "editorHoverWidget.background": c.raised,
      "editorHoverWidget.foreground": c.fg,
      "editorHoverWidget.border": c["border-strong"],
      "editorHoverWidget.statusBarBackground": c.panel,
      "editorWidget.background": c.raised,
      "editorWidget.foreground": c.fg,
      "editorWidget.border": c["border-strong"],
      "input.background": c.inset,
      "input.foreground": c.fg,
      "input.border": c["border-strong"],
      "input.placeholderForeground": c.muted,
      "inputOption.activeBackground": c.selected,
      "inputOption.activeForeground": c.fg,
      "inputOption.activeBorder": c.muted,
      "list.hoverBackground": c.hover,
      "list.hoverForeground": c.fg,
      "list.activeSelectionBackground": c.selected,
      "list.activeSelectionForeground": c.fg,
      "list.inactiveSelectionBackground": c.hover,
      "list.inactiveSelectionForeground": c.fg,
      "list.focusBackground": c.selected,
      "list.focusForeground": c.fg,
      "editorError.foreground": c.fg,
      "editorWarning.foreground": c.secondary,
      "editorOverviewRuler.border": "#00000000",
      "scrollbarSlider.background": `${c["border-strong"]}99`,
      "scrollbarSlider.hoverBackground": `${c.muted}99`,
      "scrollbarSlider.activeBackground": `${c.muted}cc`,
    },
    rules: [
      { token: "", foreground: c.fg },
      { token: "comment", foreground: c.muted, fontStyle: "italic" },
      { token: "comment.doc", foreground: c.muted, fontStyle: "italic" },
      { token: "keyword", foreground: c.fg, fontStyle: "bold" },
      { token: "keyword.directive", foreground: c.secondary },
      { token: "keyword.directive.include", foreground: c.fg },
      { token: "string", foreground: c.secondary },
      { token: "string.include.identifier", foreground: c.secondary },
      { token: "string.escape", foreground: c.fg, fontStyle: "bold" },
      { token: "string.invalid", foreground: c.fg, fontStyle: "underline" },
      { token: "number", foreground: c.fg },
      { token: "type", foreground: c.secondary },
      { token: "identifier", foreground: c.fg },
      { token: "annotation", foreground: c.secondary },
      { token: "delimiter", foreground: c.secondary },
      { token: "delimiter.bracket", foreground: c.secondary },
      { token: "delimiter.parenthesis", foreground: c.secondary },
      { token: "operator", foreground: c.secondary },
      { token: "variable", foreground: c.fg },
      { token: "function", foreground: c.fg },
    ],
  };
}

export function terminalTheme({ colors: c }: ThemePalette): ITheme {
  return {
    background: c.panel,
    foreground: c.fg,
    cursor: c.fg,
    cursorAccent: c.panel,
    selectionBackground: c.selected,
    selectionForeground: c.fg,
    selectionInactiveBackground: c.hover,
    black: c.muted,
    red: c.secondary,
    green: c.secondary,
    yellow: c.muted,
    blue: c.secondary,
    magenta: c.secondary,
    cyan: c.fg,
    white: c.fg,
    brightBlack: c.muted,
    brightRed: c.fg,
    brightGreen: c.fg,
    brightYellow: c.secondary,
    brightBlue: c.fg,
    brightMagenta: c.secondary,
    brightCyan: c.fg,
    brightWhite: c.fg,
  };
}
