if(NOT DEFINED MAINLY_LLVM_ROOT)
  message(FATAL_ERROR "MAINLY_LLVM_ROOT must point to a native LLVM 22 installation")
endif()
if(NOT DEFINED MAINLY_WASIX_SYSROOT)
  message(FATAL_ERROR "MAINLY_WASIX_SYSROOT must point to the WASIX compatibility sysroot")
endif()

set(MAINLY_LLVM_ROOT "${MAINLY_LLVM_ROOT}" CACHE PATH "Native LLVM 22 installation")
set(MAINLY_WASIX_SYSROOT "${MAINLY_WASIX_SYSROOT}" CACHE PATH "WASIX sysroot")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
  MAINLY_LLVM_ROOT
  MAINLY_WASIX_SYSROOT
)

file(TO_CMAKE_PATH "${MAINLY_LLVM_ROOT}" MAINLY_LLVM_ROOT)
file(TO_CMAKE_PATH "${MAINLY_WASIX_SYSROOT}" MAINLY_WASIX_SYSROOT)

set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER "${MAINLY_LLVM_ROOT}/bin/clang.exe")
set(CMAKE_CXX_COMPILER "${MAINLY_LLVM_ROOT}/bin/clang++.exe")
set(CMAKE_AR "${MAINLY_LLVM_ROOT}/bin/llvm-ar.exe")
set(CMAKE_RANLIB "${MAINLY_LLVM_ROOT}/bin/llvm-ranlib.exe")
set(CMAKE_NM "${MAINLY_LLVM_ROOT}/bin/llvm-nm.exe")
set(CMAKE_LINKER "${MAINLY_LLVM_ROOT}/bin/wasm-ld.exe")

set(CMAKE_C_COMPILER_TARGET wasm32-wasip1)
set(CMAKE_CXX_COMPILER_TARGET wasm32-wasip1)
set(CMAKE_SYSROOT "${MAINLY_WASIX_SYSROOT}")

set(MAINLY_WASIX_COMPILE_FLAGS
  "-matomics -mbulk-memory -mmutable-globals -pthread -mthread-model posix -ftls-model=local-exec -fno-trapping-math -D_WASI_EMULATED_MMAN -D_WASI_EMULATED_SIGNAL -D_WASI_EMULATED_PROCESS_CLOCKS -DUSE_TIMEGM"
)
set(CMAKE_C_FLAGS_INIT "${MAINLY_WASIX_COMPILE_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${MAINLY_WASIX_COMPILE_FLAGS}")

set(CMAKE_FIND_ROOT_PATH "${MAINLY_WASIX_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
